### ISSUE TITLE
Img2Img is broken with the latest version

### ISSUE THREAD

**Issue by Gushousekai195** [PladsElsker/sd-webui-inpaint-difference#29]
```
Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^
      File "D:\AI\stable-diffusion-webui\modules\call_queue.py", line 53, in f
        res = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
      File "D:\AI\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
      File "D:\AI\stable-diffusion-webui\venv\Lib\site-packages\sdwi2iextender\lib\img2img_component_injector.py", line 131, in hijack_img2img
        script_instance.resolve_image_and_mask(*script_args)
      File "D:\AI\stable-diffusion-webui\venv\Lib\site-packages\sdwi2iextender\lib\img2img_component_injector.py", line 93, in resolve_image_and_mask
        self.image = image_components[init_images_index]
                     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
    IndexError: tuple index out of range
```

Inpaint difference commit 34498adf
A1111 webui v1.10.1-4-g48239090

**Comment by PladsElsker** [comment]
Thank you for reporting! I did not test img2img apparently when updating, I will fix this asap.

**Comment by PladsElsker** [comment]
Should be fixed now.
